# Generated by Django 3.1.7 on 2021-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=300)),
                ('singer_name', models.CharField(max_length=100)),
                ('emotion_type', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='songs_images')),
                ('song', models.FileField(upload_to='songs_dir')),
            ],
        ),
    ]
