# Generated by Django 3.1.7 on 2021-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='emotion_type',
        ),
        migrations.RemoveField(
            model_name='music',
            name='singer_name',
        ),
        migrations.RemoveField(
            model_name='music',
            name='song',
        ),
        migrations.RemoveField(
            model_name='music',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='song_name',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
