# Generated by Django 3.1.7 on 2021-04-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0003_auto_20210412_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Song',
        ),
    ]
