# Generated by Django 3.1.7 on 2021-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0006_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_link',
            field=models.URLField(max_length=2000),
        ),
    ]
