# Generated by Django 3.1.7 on 2021-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Errorid', models.TextField(max_length=30, unique=True)),
                ('ErrorName', models.TextField(max_length=200)),
                ('Error_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
