# Generated by Django 3.1.7 on 2021-05-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0009_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='ErrorName',
        ),
    ]
