# Generated by Django 3.1.7 on 2021-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0010_remove_error_errorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
